# Generated by Django 4.2.7 on 2024-01-02 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название курса')),
                ('img', models.ImageField(default=None, upload_to='media/', verbose_name='Картинка')),
                ('description', models.TextField(max_length=500, verbose_name='Описание курса')),
                ('lessons_count', models.IntegerField(default=0, verbose_name='количество уроков в курсе')),
            ],
            options={
                'verbose_name': 'курс',
                'verbose_name_plural': 'курсы',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название урока')),
                ('img', models.ImageField(default=None, upload_to='media/', verbose_name='Картинка')),
                ('description', models.TextField(max_length=500, verbose_name='Описание урока')),
                ('link', models.URLField(verbose_name='Ссылка на видео')),
            ],
            options={
                'verbose_name': 'урок',
                'verbose_name_plural': 'уроки',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_date', models.DateField(verbose_name='дата оплаты')),
                ('payment_amount', models.PositiveIntegerField(verbose_name='сумма оплаты')),
                ('payment_method', models.CharField(choices=[('cash', 'cash'), ('transfer', 'transfer to the account')], default='transfer to the account', max_length=50, verbose_name='способ оплаты')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='статус платежа')),
                ('pay_id', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='id платежа stripe')),
                ('paid_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='lms_service.course', verbose_name='оплаченный курс')),
                ('paid_lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='lms_service.lesson', verbose_name='оплаченный урок')),
            ],
        ),
    ]
